<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfdd76b3d8af68fe71a43e69c8323afa3
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Faker\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Faker\\' => 
        array (
            0 => __DIR__ . '/..' . '/fzaninotto/faker/src/Faker',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfdd76b3d8af68fe71a43e69c8323afa3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfdd76b3d8af68fe71a43e69c8323afa3::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
